name: merge-to-main
run-name: ${{ github.actor }} is trying to submit a pull request to merge to main.
on:
  pull_request:
    branches:
      - main
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      # This is an action that checks out your repository onto the runner, allowing you to run scripts or other actions against your code (such as build and test tools).
      # You should use the checkout action any time your workflow will use the repository's code.
      - name: Checkout current repository.
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running unit tests
        run: |
          python3 -m pytest

  run-pylint:
    needs: run-unit-tests # ensure unit tests are successful first
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=7 $(git ls-files '*.py')
